### ISSUE TITLE
Proposition des solutions

### ISSUE THREAD

**Issue by guillaume-gc** [guillaume-gc/CodeMotion-ESI4#1]
- Extraire les informations utiles au document.
- Les traduire en terme informatique
- Proposer des solutions

**Comment by Rembos** [comment]
[Cahier des charges .docx](https://github.com/guillaume-gc/CodeMotion-ESI4/files/2952943/Cahier.des.charges.docx)

**Comment by simonhennequin** [comment]
[Partie 2.pdf](https://github.com/guillaume-gc/CodeMotion-ESI4/files/2953016/Partie.2.pdf)
