### ISSUE TITLE
Blacklog test

### ISSUE THREAD

**Issue by guillaume-gc** [guillaume-gc/CodeMotion-ESI4#10]

**Comment by macfarmeur** [comment]
Les tests unitaires et intégrations seront effectués pendant toute la phase de développement.
En effet, la solution étant nouvelle, nous n'avons aucun outil ou test précis à effectuer dessus.
En fonction de l'avancement du développement du projet, différents outils pourront être développés afin de tester l'application.
Plusieurs tests pourront être mis en place (fonctionnel , unitaires, intégration).

**Comment by guillaume-gc** [comment]
- Routage : Formulaire selection individus
- Routage : Formulaire Création publicité 
- Routage : Validation cible de routage coté serveur
- Routage : Info Cible Routage + Confirmation ou refus (texte si refus)
- Routage : Liste refus routage + texte -> Formulations selection individus + publicités
- Routage : Liste OK routage -> Bouton Envoi
- Routage : Envoi publicité coté serveur
- Saisi Commande : recherche info produit (pour calcul prix et stock)
- Saisi Commande : Formulaire règlement
- Anomalie : Recherche et enregistrement anomalie
- Anomalie : Formulaire création ticket pour une anomalie
- Anomalie : Formulaire d'édition d'une commande avec anomalie
- Anomalie : Changer status anomalie
- Anomalie : Bloquer client coté serveur 
- Référentiel : Créer un compte par un utilisateur
- Référentiel : Création script schéma et données base de donnée
- Référentiel : Liste ensemble compte pour un administrateur
- Référentiel : Liste ensemble commandes pour un administrateur
- Référentiel : Liste ensemble articles pour un administrateur
