### ISSUE TITLE
Estimation Contractuelle

### ISSUE THREAD

**Issue by guillaume-gc** [guillaume-gc/CodeMotion-ESI4#14]

**Comment by Rembos** [comment]
Liste résultats demandés

Formulaire : 
-	Formulaire renseignements données personnes
-	Formulaire création publicité
-	Formulaire de validation des cibles
-	Formulaire envoie des publicités
-	Formulaire création de compte
-	Formulaire de commande
-	Formulaire de recherche d’anomalies
-	Formulaire de paiement
-	Formulaire de création d’un ticket

Écrans :
-	Affichage des comptes
-	Affichage des cibles de routages validées/en attente de validation
-	Affichage des commandes
-	Affichage des anomalies
-	Affichage des paiements
-	Affichage des tickets


Messages :
-	Validation :
o	Envoie d’un mail/notification au directeur de stratégie lui permettant de vérifier et valider la cible de routage.
o	Possibilité de refuser la cible de routage : envoyer mail/notification au créateur de la cible de routage en précisant le motif du refus et les modifications à apporter pour la valider.
o	Verrouillage de l’édition et de l’envoie des cibles de routages tant qu’elles ne sont pas validées
-	Envoie des infos publicités :
o	Envoie d’un mail/notification au responsable avec la cible de routage valide
o	Envoie du fichier XML contenant les informations de la cible
o	Le support de la publicité
-	Commande :
o	Envoie des infos à la BDD
o	Transmission au logiciel de gestion des stocks
-	Anomalie :
o	Envoie message en fonction de l’anomalie enregistrée sur la BDD
-	Tickets :
o	Envoie des tickets + infos

R = 25
Liste fichiers logiques 

BDD : FENOUIL
Tables :
-	Administrateur
-	EmployeProspect
-	Critere_Selection
-	Individu
-	Article
-	Commande
-	Client
-	Gestionnaire_Administratif
-	Assistant_Saisie

F=9
Nombre d’unité de programmation
N = (25+9)*1.5=51
N=51
Charge d’étude technique
AOG = (10+51/5)*2=40,4
AOG=40J et 10h
Charge des dossiers de programme
AOD=2*51=102
AOD= 102J
Charge de réalisation et test
PROG = 51*5=255
PROG=255J
Charge d’intégration et de recette
REC = (10+51/10)*2
REC=30,2J

**Comment by simonhennequin** [comment]
Liste résultats demandés
Formulaire :
Formulaire renseignements données personnes 
Formulaire création publicité 
Formulaire de validation des cibles 
Formulaire envoie des publicités 
Formulaire création de compte 
Formulaire de commande 
Formulaire de recherche d’anomalies 
Formulaire de paiement 
Formulaire de création d’un ticket 
Écrans :
Affichage des comptes 
Affichage des cibles de routages validées/en attente de validation 
Affichage des commandes 
Affichage des anomalies 
Affichage des paiements 
Affichage des tickets 
Messages :
Validation :
o Envoie d’un mail/notification au directeur de stratégie lui permettant de vérifier et valider la cible de routage.
o Possibilité de refuser la cible de routage : envoyer mail/notification au créateur de la cible de routage en précisant le motif du refus et les modifications à apporter pour la valider.
o Verrouillage de l’édition et de l’envoie des cibles de routages tant qu’elles ne sont pas validées 
Envoie des infos publicités :
o Envoie d’un mail/notification au responsable avec la cible de routage valide
o Envoie du fichier XML contenant les informations de la cible
o Le support de la publicité 
Commande :
o Envoie des infos à la BDD
o Transmission au logiciel de gestion des stocks 
Anomalie :
o Envoie message en fonction de l’anomalie enregistrée sur la BDD 
Tickets :
o Envoie des tickets + infos 


R = 25
Liste fichiers logiques
BDD : FENOUIL
Tables :
Administrateur 
EmployeProspect 
Critere_Selection 
Individu 
Article 
Commande 
Client 
Gestionnaire_Administratif 
Assistant_Saisie 

F=9
Nombre d’unité de programmation
N = (25+9)1.5=51
N=51
Charge d’étude technique
AOG = (10+51/5)2=40,4
AOG=40J et 10h
Charge des dossiers de programme
AOD=251=102
AOD= 102J
Charge de réalisation et test
PROG = 515=255
PROG=255J
Charge d’intégration et de recette
REC = (10+51/10)*2
REC=30,2J
