### ISSUE TITLE
Architecture Fonctionnelle

### ISSUE THREAD

**Issue by guillaume-gc** [guillaume-gc/CodeMotion-ESI4#16]
Déterminer et décrire les acteurs et les cas d’utilisation du système.
Décrire sous forme de diagramme de séquence de niveau système le cas d’utilisation « Saisir une commande ».

**Comment by Rembos** [comment]
![image](https://user-images.githubusercontent.com/12511852/55641512-5a37da00-57ce-11e9-94e7-0898f98c2c39.png)

**Comment by Rembos** [comment]
<img width="994" alt="Capture d’écran 2019-04-05 à 18 10 58" src="https://user-images.githubusercontent.com/12511852/55643096-98cf9380-57d2-11e9-9aa1-93b346ec5d69.png">
