### ISSUE TITLE
Analyse d'Objet : Modèle Dynamique

### ISSUE THREAD

**Issue by guillaume-gc** [guillaume-gc/CodeMotion-ESI4#18]
Créer les diagrammes de séquence objet pour quelques cas d’utilisation les plus significatifs.
Créer les diagrammes d’états nécessaires.

**Comment by simonhennequin** [comment]
![DiagEtat_AnoPaye](https://user-images.githubusercontent.com/16338402/55686413-1fb27680-5961-11e9-9a2f-74624d520286.PNG)
![DiagSeq_TraitAno](https://user-images.githubusercontent.com/16338402/55686414-250fc100-5961-11e9-8f75-679ec29fdf70.PNG)
