### ISSUE TITLE
Schéma base de données

### ISSUE THREAD

**Issue by guillaume-gc** [guillaume-gc/CodeMotion-ESI4#3]
Faire un schéma UML de la base de données

**Comment by CLStrife** [comment]
![image](https://user-images.githubusercontent.com/35105359/54137891-bea98880-441e-11e9-821e-ea732e035f52.png)

**Comment by CLStrife** [comment]
![image](https://user-images.githubusercontent.com/35105359/54305959-a1182280-45c8-11e9-85af-efa1db2e0c9c.png)

**Comment by CLStrife** [comment]
![image](https://user-images.githubusercontent.com/35105359/54306061-d7ee3880-45c8-11e9-996e-4f549cfc1930.png)
