### ISSUE TITLE
Blacklog recette

### ISSUE THREAD

**Issue by guillaume-gc** [guillaume-gc/CodeMotion-ESI4#8]

**Comment by Rembos** [comment]
Expression des besoins techniques :
Cahier des charges
- Élaboration du cahier des charges avec le client. 

Design général 
- Élaboration du design de l'application avec le client.

Infrastructure (serveurs…) 
        - Expression des besoins et possibilités pour l'application avec le client.

Technologie 
        - Explication des technologies utilisées pour la réalisation du projet.

Cahier de test 
        - Tests fonctionnels (créé avec les testeurs).
        - Tests techniques (créé avec les testeurs).

Cahier de recette
        - Résultats des tests effectués par les testeurs.

Remontée des problèmes (application, infrastructure) 
        - Rapport des erreurs avec l'équipe de développement en fonction des tests             effectuées.
        -  Vérification de la pertinence de l’application par rapport aux demandes client (test         d'acceptation).

Documentation client :
Manuel utilisateur (cahier fonctionnel) 
        - Livraison au client d'une notice utilisateur qui explique la partie fonctionnelle de         l'application.
